package com.skyline.org.auth.audit;

public enum AuthEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTER,
    EMAIL_VERIFIED,
    RESEND_VERIFICATION,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET,
    ACCOUNT_LOCKED,
    RATE_LIMITED,
    ADMIN_USER_UPDATED,
    MFA_ENROLLED,
    MFA_CHALLENGE_SUCCESS,
    MFA_CHALLENGE_FAILURE
}
